/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.calculatorapp;

/**
 *
 * @author samuelalake
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    
    String currentDisplayText;
    String isWhatOperation;
    String sub1, sub2;
    
    public calculator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        displayPanel = new javax.swing.JPanel();
        displayText = new javax.swing.JLabel();
        digitsPanel = new javax.swing.JPanel();
        divisionButton = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        numberPoint = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Samuel's Simple Calculator");
        setBackground(new java.awt.Color(0, 0, 0));

        displayPanel.setBackground(new java.awt.Color(60, 60, 60));

        displayText.setFont(new java.awt.Font("SF Pro Rounded", 0, 62)); // NOI18N
        displayText.setForeground(new java.awt.Color(255, 255, 255));
        displayText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(displayText, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayText, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        digitsPanel.setBackground(new java.awt.Color(0, 0, 0));

        divisionButton.setBackground(new java.awt.Color(165, 165, 165));
        divisionButton.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        divisionButton.setText("÷");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        number7.setBackground(new java.awt.Color(51, 51, 51));
        number7.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number7.setForeground(new java.awt.Color(255, 255, 255));
        number7.setText("7");
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number4.setBackground(new java.awt.Color(51, 51, 51));
        number4.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number4.setForeground(new java.awt.Color(255, 255, 255));
        number4.setText("4");
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        number1.setBackground(new java.awt.Color(51, 51, 51));
        number1.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number1.setForeground(new java.awt.Color(255, 255, 255));
        number1.setText("1");
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number0.setBackground(new java.awt.Color(51, 51, 51));
        number0.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number0.setForeground(new java.awt.Color(255, 255, 255));
        number0.setText("0");
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        multiplicationButton.setBackground(new java.awt.Color(165, 165, 165));
        multiplicationButton.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        multiplicationButton.setText("×");
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonActionPerformed(evt);
            }
        });

        subtractionButton.setBackground(new java.awt.Color(165, 165, 165));
        subtractionButton.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        subtractionButton.setText("−");
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonActionPerformed(evt);
            }
        });

        additionButton.setBackground(new java.awt.Color(165, 165, 165));
        additionButton.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        additionButton.setText("+");
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });

        number8.setBackground(new java.awt.Color(51, 51, 51));
        number8.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number8.setForeground(new java.awt.Color(255, 255, 255));
        number8.setText("8");
        number8.setToolTipText("");
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        number9.setBackground(new java.awt.Color(51, 51, 51));
        number9.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number9.setForeground(new java.awt.Color(255, 255, 255));
        number9.setText("9");
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(51, 51, 51));
        clearButton.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("AC");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        number5.setBackground(new java.awt.Color(51, 51, 51));
        number5.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number5.setForeground(new java.awt.Color(255, 255, 255));
        number5.setText("5");
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number6.setBackground(new java.awt.Color(51, 51, 51));
        number6.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number6.setForeground(new java.awt.Color(255, 255, 255));
        number6.setText("6");
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        number2.setBackground(new java.awt.Color(51, 51, 51));
        number2.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number2.setForeground(new java.awt.Color(255, 255, 255));
        number2.setText("2");
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });

        number3.setBackground(new java.awt.Color(51, 51, 51));
        number3.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        number3.setForeground(new java.awt.Color(255, 255, 255));
        number3.setText("3");
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        numberPoint.setBackground(new java.awt.Color(51, 51, 51));
        numberPoint.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        numberPoint.setForeground(new java.awt.Color(255, 255, 255));
        numberPoint.setText(".");
        numberPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberPointActionPerformed(evt);
            }
        });

        enterButton.setBackground(new java.awt.Color(254, 158, 11));
        enterButton.setFont(new java.awt.Font("SF Pro Rounded", 0, 31)); // NOI18N
        enterButton.setForeground(new java.awt.Color(255, 255, 255));
        enterButton.setText("=");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout digitsPanelLayout = new javax.swing.GroupLayout(digitsPanel);
        digitsPanel.setLayout(digitsPanelLayout);
        digitsPanelLayout.setHorizontalGroup(
            digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digitsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(digitsPanelLayout.createSequentialGroup()
                        .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(digitsPanelLayout.createSequentialGroup()
                                .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(digitsPanelLayout.createSequentialGroup()
                                .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(digitsPanelLayout.createSequentialGroup()
                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(digitsPanelLayout.createSequentialGroup()
                                        .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(digitsPanelLayout.createSequentialGroup()
                                        .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(digitsPanelLayout.createSequentialGroup()
                        .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numberPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        digitsPanelLayout.setVerticalGroup(
            digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digitsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(digitsPanelLayout.createSequentialGroup()
                        .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(digitsPanelLayout.createSequentialGroup()
                        .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(digitsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(digitsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "1");
    }//GEN-LAST:event_number1ActionPerformed

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "0");
    }//GEN-LAST:event_number0ActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "2");
    }//GEN-LAST:event_number2ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "3");
    }//GEN-LAST:event_number3ActionPerformed

    private void numberPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberPointActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + ".");
    }//GEN-LAST:event_numberPointActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        double result = 0;
        
        String inputToSolve = displayText.getText();
        createSubstring(inputToSolve, ' ', 2);
        String firstValue = sub1;
        String secondValue = sub2;
        
        switch(isWhatOperation){
            case "division":
                result = Double.parseDouble(firstValue) / Double.parseDouble(secondValue);
                break;
            case "multiplication":
                result = Double.parseDouble(firstValue) * Double.parseDouble(secondValue);
                break;
            case "subtraction":
                result = Double.parseDouble(firstValue) - Double.parseDouble(secondValue);
                break;
            case "addition":
                result = Double.parseDouble(firstValue) + Double.parseDouble(secondValue);
                break;
        }
        
        String resultToDisplay = Double.toString(result);
        createSubstring(resultToDisplay, '.', 1);
        String beforePoint = sub1;
        String afterPoint = sub2;
        
        
        if(afterPoint.equals("0")){
            displayText.setText(beforePoint);
        }else{
            displayText.setText(resultToDisplay);
        }
        
    }//GEN-LAST:event_enterButtonActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "7");
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "8");
    }//GEN-LAST:event_number8ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "9");
    }//GEN-LAST:event_number9ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "4");
    }//GEN-LAST:event_number4ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "5");
    }//GEN-LAST:event_number5ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        // TODO add your handling code here:
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + "6");
    }//GEN-LAST:event_number6ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        displayText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        // TODO add your handling code here:
        isWhatOperation = "division";
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + " ÷ ");
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void multiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonActionPerformed
        // TODO add your handling code here:
        isWhatOperation = "multiplication";
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + " × ");
    }//GEN-LAST:event_multiplicationButtonActionPerformed

    private void subtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonActionPerformed
        // TODO add your handling code here:
        isWhatOperation = "subtraction";
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + " − ");
    }//GEN-LAST:event_subtractionButtonActionPerformed

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed
        // TODO add your handling code here:
        isWhatOperation = "addition";
        currentDisplayText = displayText.getText();
        displayText.setText(currentDisplayText + " + ");
    }//GEN-LAST:event_additionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }
    
    public void createSubstring(String mainString, char separatingChar, int separatorCount){
        int separatorCounter = 0;
        sub1 = ""; sub2 = "";
        for(int i = 0; i < mainString.length(); i++){ 
            
            if(mainString.charAt(i) != separatingChar && separatorCounter == 0){
                sub1 += mainString.charAt(i);
            }else if(mainString.charAt(i) == separatingChar){
                separatorCounter++;
            }else if(separatorCounter == separatorCount){
                sub2 += mainString.charAt(i);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel digitsPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel displayText;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton numberPoint;
    private javax.swing.JButton subtractionButton;
    // End of variables declaration//GEN-END:variables
}
